# Generated by Django 4.2.2 on 2023-06-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
